import { useState } from 'react'
import { NextPage } from 'next'
import Head from 'next/head'
import { Button, Input, Upload, notification } from 'antd'
import { InboxOutlined, CopyFilled, CopyOutlined } from '@ant-design/icons';
import 'antd/dist/antd.min.css'
import copy from 'copy-to-clipboard'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
const { Dragger } = Upload

const Home: NextPage = () => {
  const [url, setUrl] = useState('')
  const [name, setName] = useState('')

  function handleUpload(e: any) {
    const formData = new FormData()
    formData.append('name', 'file')
    const file = e.target.files[0]
    formData.append(file.name, file)
    formData.append(file.name, file)
    const xhr = new XMLHttpRequest()
    xhr.open('POST', '/api/upload')
    xhr.send(formData)
  }

  function onChange(data: any) {
    console.log('%c [ info ]-23', 'font-size:13px; background:pink; color:#bf2c9f;', data)
    if(data.name) {
      setName(data.name)
    }
    if (data.fileList.length && data.fileList[0].response?.url) {
      setUrl(data.fileList[0].response.url)
    } else {
      setUrl('')
    }
    // if (info.file.status === 'done') {
    //   message.success(`${info.file.name} file uploaded successfully`);
    // } else if (info.file.status === 'error') {
    //   message.error(`${info.file.name} file upload failed.`);
    // }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Starboard Uploader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} style={{ marginBottom: 80 }}>
          Starboard Uploader
        </h1>
          {/* <div>
            <Input type="file" id="files" onChange={(e) => {
              handleUpload(e)
            }} />
          </div>
          <div>
            <Upload listType="picture" name="file" action={'/api/upload'}>
              <Button>Upload</Button>
            </Upload>
          </div> */}
        <div className={styles.uploader}>
          <Dragger listType={'picture'} maxCount={1} onChange={onChange} name="file" action={'/api/upload'} style={{ padding: '24px 48px', minWidth: 400, width: 400, height: 240, maxHeight: 200 }}>
            <p className="ant-upload-drag-icon">
              <InboxOutlined />
            </p>
            <p className="ant-upload-text">Click or drag file to this area to upload</p>
          </Dragger>
          <section>
            {url ? <div>
              <div onClick={() => {
                window.open(`${url}`)
              }} style={{ backgroundImage: `url(${url})`, backgroundSize: 'contain', backgroundRepeat: 'no-repeat', height: 240, cursor: 'pointer' }} />
              <div style={{ wordBreak: 'break-all', lineHeight: 1.2, color: '#666', marginTop: 24 }}>URL: {url}<CopyOutlined onClick={() => {
                copy(url)
                notification.success({
                  message: 'Copied Success!'
                })
              }} style={{ color: '#40a9ff', marginLeft: 4, cursor: 'pointer' }} /></div>
            </div> : <div style={{ color: '#666' }}>Waiting for upload.</div>}
          </section>
        </div>
      </main>
    </div>
  )
}

export default Home
