import { useState } from 'react'
import { NextPage } from 'next'
import Head from 'next/head'
import { Upload, notification } from 'antd'
import { InboxOutlined, CopyOutlined } from '@ant-design/icons'
import 'antd/dist/antd.min.css'
import copy from 'copy-to-clipboard'

import styles from '../styles/Home.module.css'
const { Dragger } = Upload

interface UploadChangeParam {
  name?: string
  fileList: Array<{
    response?: {
      url: string
    }
  }>
}

const Home: NextPage = () => {
  const [url, setUrl] = useState('')

  function onChange (data: UploadChangeParam) {
    console.log(
      '%c [ info ]-23',
      'font-size:13px; background:pink; color:#bf2c9f;',
      data
    )
    if (data.fileList.length && data.fileList[0].response?.url) {
      setUrl(data.fileList[0].response.url)
    } else {
      setUrl('')
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Starboard Uploader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} style={{ marginBottom: 80 }}>
          Starboard Uploader
        </h1>
        <div className={styles.uploader}>
          <Dragger
            listType={'picture'}
            maxCount={1}
            onChange={onChange}
            name="file"
            action={'/api/upload'}
            style={{
              padding: '24px 48px',
              minWidth: 400,
              width: 400,
              height: 240,
              maxHeight: 200
            }}
          >
            <p className="ant-upload-drag-icon">
              <InboxOutlined />
            </p>
            <p className="ant-upload-text">
              Click or drag file to this area to upload
            </p>
          </Dragger>
          <section>
            {url
              ? (
                  <div>
                    <div
                      onClick={() => {
                        window.open(`${url}`)
                      }}
                      style={{
                        backgroundImage: `url(${url})`,
                        backgroundSize: 'contain',
                        backgroundRepeat: 'no-repeat',
                        height: 240,
                        cursor: 'pointer'
                      }}
                    />
                    <div
                      style={{
                        wordBreak: 'break-all',
                        lineHeight: 1.2,
                        color: '#666',
                        marginTop: 24
                      }}
                    >
                      URL: {url}
                      <CopyOutlined
                        onClick={() => {
                          copy(url)
                          notification.success({
                            message: 'Copied Success!'
                          })
                        }}
                        style={{
                          color: '#40a9ff',
                          marginLeft: 4,
                          cursor: 'pointer'
                        }}
                      />
                    </div>
                  </div>
                )
              : (
                  <div style={{ color: '#666' }}>Waiting for upload.</div>
                )}
          </section>
        </div>
      </main>
    </div>
  )
}

export default Home
